name: collect stock mentions

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install packages
        run: pip install requests

      - name: run script
        run: python scripts/collect_data.py

      - name: commit data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/mentions.csv
          git commit -m "update mentions data"
          git push
